In [1]:
import pathlib
import pandas as pd

In [2]:
biolog_folder = pathlib.Path("../../data/raw/biolog/")
features_folder = biolog_folder  / "features"
phenotypes_folder = biolog_folder  / "phenotypes"

rast_features_file = features_folder / "rast-annotations.tsv"
ch_phenotype_file = phenotypes_folder / "p_CH_phenotypes.tsv"
leaf_phenotype_file = phenotypes_folder / "p_LEAF_phenotypes.tsv"
pmi_phenotype_file = phenotypes_folder / "p_PMI_phenotypes.tsv"

In [3]:
from trait_prediction.utils import read_generic_features

In [4]:
rast_feature_df = read_generic_features(rast_features_file, bool_conversion=False)
rast_feature_df.index = [r.rstrip('.RAST') for r in rast_feature_df.index]
rast_feature_df

,SSO:000020980,SSO:000009137,SSO:000009247,SSO:000001565,SSO:000021809,SSO:000003942,SSO:000001181,SSO:000021589,SSO:000019329,SSO:000021906,...,SSO:000026214,SSO:000018244,SSO:000018771,SSO:000010818,SSO:000022096,SSO:000024346,SSO:000017482,SSO:000014980,SSO:000014981,SSO:000010230
13689.6,1,1857,5,6,3,3,2,3,1,1,...,0,0,0,0,0,0,0,0,0,0
Pseudomonas_sp._GM18_2511231007.fna,3,283,0,1,0,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
Pseudomonas_sp._GV021_2738541271.fna,4,189,0,1,0,1,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
38305.14,2,677,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
Methylibium_sp._CF059_2585428062.fna,2,806,0,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Novosphingobium_sp._CF614_2687453689.fna,1,533,1,2,1,2,1,2,0,0,...,0,0,0,0,0,0,0,0,0,0
Brevibacillus_sp._OK042_2687453682.fna,1,845,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
Dyella_sp._YR388_2739367700.fna,3,584,0,1,0,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
Burkholderia_sp._OK233_2711768632.fna,5,630,1,5,0,1,1,4,7,0,...,0,0,0,0,1,0,0,0,0,0
GCF_003258395.1,0,818,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [45]:
ch_phenotype_df = pd.read_csv(ch_phenotype_file, sep="\t", index_col=0).astype('Int64')
ch_phenotype_df.columns = [f"{c}--ch_biolog" for c in ch_phenotype_df.columns]
ch_phenotype_df.index = [r.lstrip("g") for r in ch_phenotype_df.index] # type: ignore
ch_phenotype_df.index.name = "genomeID"
leaf_phenotype_df = pd.read_csv(leaf_phenotype_file, sep="\t", index_col=0).astype('Int64')
leaf_phenotype_df.columns = [f"{c}--leaf_biolog" for c in leaf_phenotype_df.columns]
pmi_phenotype_df = pd.read_csv(pmi_phenotype_file, sep="\t", index_col=0).astype('Int64')
pmi_phenotype_df.columns = [f"{c}--pmi_biolog" for c in pmi_phenotype_df.columns]

In [46]:
ch_phenotype_df

,Carbon-D-Trehalose--ch_biolog,Carbon-N-Acetyl-b-D-Mannosamine--ch_biolog,Carbon-Salicin--ch_biolog,Carbon-Pectin--ch_biolog,Carbon-Dextrin--ch_biolog,Carbon-a-Hydroxy-Butyric-Acid--ch_biolog,Carbon-L-Fucose--ch_biolog,Carbon-a-D-Lactose--ch_biolog,Carbon-Citric-Acid--ch_biolog,Carbon-Acetic-Acid--ch_biolog,...,Carbon-L-Lactic-Acid--ch_biolog,Carbon-a-Keto-Glutaric-Acid--ch_biolog,Carbon-D-Fructose--ch_biolog,Carbon-L-Aspartic-Acid--ch_biolog,Carbon-N-Acetyl-Neuraminic-Acid--ch_biolog,Carbon-D-Glucose--ch_biolog,Carbon-D-Galactonic-Acid-g-Lactone--ch_biolog,Carbon-D-Mannose--ch_biolog,Carbon-Glycerol--ch_biolog,Carbon-Glycyl-L-Proline--ch_biolog
genomeID,,,,,,,,,,,,,,,,,,,,,
149698.22,1,1,1,1,1,1,<NA>,1,1,1,...,1,1,1,0,1,1,<NA>,1,1,1
702115.9,0,0,0,1,0,1,<NA>,0,1,1,...,1,1,1,1,0,1,<NA>,1,1,1
1663.218,1,0,1,1,1,1,<NA>,1,1,1,...,1,1,1,1,1,1,<NA>,1,1,1
242605.18,1,0,1,1,1,1,<NA>,1,1,1,...,1,1,1,1,1,1,<NA>,1,1,1
134536.40,0,0,0,1,0,1,<NA>,1,1,1,...,1,1,1,1,0,1,<NA>,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134536.48,1,0,1,1,0,0,<NA>,1,1,1,...,1,1,1,1,1,1,<NA>,1,1,1
693973.6,0,0,0,0,1,0,0,0,0,1,...,1,1,0,0,0,0,0,0,0,0
754262.3,1,<NA>,<NA>,<NA>,1,1,<NA>,1,<NA>,0,...,<NA>,1,1,1,<NA>,1,<NA>,1,<NA>,<NA>
1883.1831,1,0,1,1,0,0,<NA>,1,1,1,...,1,1,1,1,1,1,<NA>,1,1,1
242606.52,1,0,1,1,0,0,<NA>,1,1,1,...,1,1,1,1,1,1,<NA>,1,1,1

In [47]:
processed_folder = pathlib.Path("../../data/processed/biolog/")

processed_phenotypes_folder = processed_folder / "phenotypes"
processed_features_folder = processed_folder / "features"

In [48]:
ch_phenotype_output = processed_phenotypes_folder / "ch_phenotypes.tsv"
leaf_phenotype_output = processed_phenotypes_folder / "leaf_phenotypes.tsv"
pmi_phenotype_output = processed_phenotypes_folder / "pmi_phenotypes.tsv"
ch_phenotype_df.to_csv(ch_phenotype_output, index=True, sep="\t")
leaf_phenotype_df.to_csv(leaf_phenotype_output, index=True, sep="\t")
pmi_phenotype_df.to_csv(pmi_phenotype_output, index=True, sep="\t")

In [9]:
genomes = [r.rstrip('.RAST') for r in rast_feature_df.index]

In [10]:
# Missing from genomes in ch phenotypes not in features
len(set(ch_phenotype_df.index) - set(genomes))

0

In [11]:
# Missing from genomes in leaf phenotypes not in features
len(set(leaf_phenotype_df.index) - set(genomes)) / len(set(leaf_phenotype_df.index)) * 100

50.48543689320388

In [12]:
# Missing from genomes in pmi phenotypes not in features
len(set(pmi_phenotype_df.index) - set(genomes))

0

## Split feature tables for each biolog dataset

In [39]:
def split_data(data: pd.DataFrame, rows: pd.Index) -> pd.DataFrame:
    try:
        new_data = data.loc[rows, :]
    except KeyError:
        print("Missing keys")
        com_rows = list(set(rows).intersection(set(data.index)))
        new_data = data.loc[com_rows, :]
    new_data.index.name = "genomeID"
    return new_data.loc[new_data.any(axis=1), new_data.any(axis=0)]

In [40]:
ch_rast_feature_df = split_data(rast_feature_df, ch_phenotype_df.index)

In [41]:
leaf_rast_feature_df = split_data(rast_feature_df, leaf_phenotype_df.index)

Missing keys

In [42]:
pmi_rast_feature_df = split_data(rast_feature_df, pmi_phenotype_df.index)

In [43]:
print(f"CH={ch_rast_feature_df.shape}, PMI={pmi_rast_feature_df.shape}, Leaf={leaf_rast_feature_df.shape}")

CH=(362, 15770), PMI=(55, 9079), Leaf=(102, 2111)

In [44]:
rast_ch_output = processed_features_folder / "rast_ch_features.tsv"
ch_rast_feature_df.to_csv(rast_ch_output, sep="\t", index=True)
rast_leaf_output = processed_features_folder / "rast_leaf_features.tsv"
leaf_rast_feature_df.to_csv(rast_leaf_output, sep="\t", index=True)
rast_pmi_output = processed_features_folder / "rast_pmi_features.tsv"
pmi_rast_feature_df.to_csv(rast_pmi_output, sep="\t", index=True)

In [56]:
'1663.25' in ch_phenotype_df.index

False