In [35]:
import pathlib

import numpy as np
import pandas as pd

In [36]:
from ete3 import Tree

In [37]:
from splitter import RandomSplitter, LargeTreeTraverseOOCSplitter

## Read phenotype and feature data

Get X and y

In [38]:
data_folder = pathlib.Path("../../data/processed/biolog/")

In [39]:
from trait_prediction.main import PhenotypeSet, PhenotypeIndex
from trait_prediction.utils import read_generic_features

In [40]:
pheno_file = data_folder / "phenotypes/leaf_phenotypes.tsv"
# feature_file = data_folder / "features_reduced/kofam/kofam_leaf_features_reduced.tsv"
feature_file = data_folder / "features_combined/leaf/Alanine_features_combined.tsv"
pheno_file.is_file(), feature_file.is_file()

(True, True)

In [41]:
phenotype_index = PhenotypeIndex(name="Alanine", category="leaf_biolog")

In [42]:
def generate_data(pheno_file, feature_file, phenotype_index):
    phenotypeset = PhenotypeSet.read_data(pheno_file)
    phenotype = phenotypeset[phenotype_index]
    feature = read_generic_features(
        feature_file, bool_conversion=True, dtype="uint8"
    )
    common_index = list(set(phenotype.phenotype_data.index) & set(feature.index))
    y = phenotype.phenotype_data.loc[common_index]
    X = feature.loc[common_index]
    return X, y, common_index

In [43]:
X, y, common_index = generate_data(pheno_file, feature_file, phenotype_index)

In [44]:
X

,1215_4813,1393_3616,120_6721,1325_2712,1365_1863,992_228,989_480,1363_5044,733_1793,1132_1453,...,UniRef70_UPI00226A1AF4,UniRef70_A0A2U1C6J9,UniRef70_UPI0013A68AD7,UniRef70_A0A1B1BIY0,UniRef70_UPI001E3CF035,UniRef70_A0A097EEC4,UniRef70_A0A3R9AME7,UniRef70_UPI001C87EFB6,UniRef70_A0A3C1DZ99,UniRef70_A0A1E5MF57
genomeID,,,,,,,,,,,,,,,,,,,,,
GCF_001422405.1,0,1,0,0,1,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
GCF_001422165.1,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
GCF_001422425.1,0,0,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
GCF_001421605.1,1,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
GCF_001421665.1,1,1,0,1,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GCF_001421535.1,1,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
GCF_001423125.1,1,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
GCF_003258395.1,1,0,0,0,0,1,0,1,1,0,...,0,0,0,0,0,0,1,0,0,0
GCF_001425445.1,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GCF_001424045.1,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [45]:
y

genomeID
GCF_001422405.1    1
GCF_001422165.1    0
GCF_001422425.1    0
GCF_001421605.1    1
GCF_001421665.1    1
                  ..
GCF_001421535.1    1
GCF_001423125.1    1
GCF_003258395.1    1
GCF_001425445.1    0
GCF_001424045.1    1
Name: Alanine--leaf_biolog, Length: 195, dtype: uint8

## Read the tree and create train/test split

Create X_train, X_test, y_train, y_test

In [46]:
tree_file = pathlib.Path("../../data/processed/biolog/phylogeny/v2_all_combined_trimmed_tree-labels.newick")
tree_file.is_file()

True

In [47]:
tree = Tree(str(tree_file), format=1)
tree

Tree node '' (0x7f8a3ae50a9)

In [48]:
# Get the number of leaves in the tree
len(tree)

1361

In [49]:
tree.get_leaf_names()

['Chitinophaga_sp._OK723_2757320416.fna',
 'Chitinophaga_sp._YR573_2690315653.fna',
 'Chitinophaga_sp._CF118_2687453677.fna',
 'Chitinophaga_sp._CF418_2609459644.fna',
 'Chitinophaga_sp._YR627_2693429788.fna',
 'Niastella_sp._CF465_2738541278.fna',
 'Filimonas_sp._YR581_2757320532.fna',
 'FW305-C-49.genome',
 'FW305-C-271.genome',
 'FW305-C-272.genome',
 'FW305-C-21.genome',
 'Hymenobacter_sp._YR204_2739367866.fna',
 '926556.3.RAST',
 'GW458-12-2-14-TSB2.genome',
 'Larkinella_sp._BK230_2802428837.fna',
 'GCF_001424405.1.fna',
 'Dyadobacter_sp._SG02_2609459762.fna',
 'Mucilaginibacter_sp._OK098_2609459642.fna',
 'Mucilaginibacter_sp._OV119_2757320427.fna',
 'Mucilaginibacter_sp._YR332_2616644844.fna',
 'Mucilaginibacter_sp._OK268_2690315638.fna',
 'Mucilaginibacter_sp._OK283_2684623006.fna',
 'Pedobacter_sp._OK701_2738541283.fna',
 'FW305-3-2-15-E-R2A2.genome',
 'Pedobacter_sp._YR016_2738541284.fna',
 'Pedobacter_sp._OK628_2738543023.fna',
 'Pedobacter_sp._OK626_2609459674.fna',
 'GCF_001424305.1.fna',
 'GCF_001423945.1.fna',
 'Pedobacter_sp._CF523_2739367656.fna',
 'GCF_920984665.1.fna',
 'GCF_920984735.1.fna',
 'Pedobacter_sp._YR510_2739367663.fna',
 'GCF_001421515.1.fna',
 'Pedobacter_sp._CF074_2738541302.fna',
 'Pedobacter_sp._OV280_2757320436.fna',
 'Pedobacter_sp._OK291_2739367651.fna',
 'GW460-11-11-14-LB5.genome',
 'GW460-11-11-14-TSB4.genome',
 '1986952.3.RAST',
 '226186.12.RAST',
 'GCF_001423985.1.fna',
 'GW456-11-11-14-LB4.genome',
 'Flavobacterium_sp._FV08_2615840595.fna',
 'Flavobacterium_sp._CF108_2693429823.fna',
 '237.95.RAST',
 '237.93.RAST',
 '237.94.RAST',
 'Flavobacterium_sp._GV028_2739367858.fna',
 'Flavobacterium_sp._GV029_2739367857.fna',
 'Flavobacterium_sp._CF136_2513020052.fna',
 'GCF_001422725.1.fna',
 'Flavobacterium_sp._OV086_2609459741.fna',
 'Flavobacterium_sp._GV069_2738541279.fna',
 'Flavobacterium_sp._GV030_2738541285.fna',
 'Flavobacterium_sp._GV063_2738543007.fna',
 'Elizabethkingia_sp._YR214_2738541273.fna',
 'Elizabethkingia_sp._YR191_2738543014.fna',
 'GCF_001424585.1.fna',
 'Chryseobacterium_sp._OV259_2582581873.fna',
 'Chryseobacterium_sp._YR005_2585428095.fna',
 'GCF_001424105.1.fna',
 'GCF_001424145.1.fna',
 'GCF_920984705.1.fna',
 'Chryseobacterium_sp._CF356_2585428061.fna',
 'GCF_001425355.1.fna',
 'Chryseobacterium_sp._YR561_2585428115.fna',
 'Chryseobacterium_sp._YR460_2585428187.fna',
 'Chryseobacterium_sp._CF299_2582581282.fna',
 'Chryseobacterium_sp._CF284_2582581281.fna',
 'Chryseobacterium_populi_CF314_2511231000.fna',
 'Chryseobacterium_sp._YR203_2588254257.fna',
 'Chryseobacterium_sp._OV279_2588253712.fna',
 'Chryseobacterium_sp._OV715_2585428060.fna',
 'Chryseobacterium_sp._YR221_2588254255.fna',
 'Chryseobacterium_sp._OV705_2585428045.fna',
 'Chryseobacterium_sp._CF365_2582581278.fna',
 'Chryseobacterium_sp._YR477_2585428182.fna',
 'Chryseobacterium_sp._YR480_2585428184.fna',
 'Chryseobacterium_sp._YR459_2585428185.fna',
 'Chryseobacterium_sp._YR485_2585428183.fna',
 '1303.43.RAST',
 'Tumebacillus_sp._BK434_2795386103.fna',
 'Brevibacillus_sp._OK042_2687453682.fna',
 'GCF_001423865.2.fna',
 'Brevibacillus_sp._BC25_2512564013.fna',
 'Brevibacillus_sp._CF112_2510917027.fna',
 'FW301-21C12A.genome',
 'FW306-2-1A-C05A.genome',
 'FW126-R14.genome',
 '2654975.3.RAST',
 'Paenibacillus_sp._YR247_2615840634.fna',
 'Paenibacillus_chondroitinus_OK414_2585428059.fna',
 'FW306-2-2C-A10BC.genome',
 '1333534.3.RAST',
 'Paenibacillus_sp._BK673_2795386125.fna',
 'Paenibacillus_sp._PDC88_2693429827.fna',
 'FW104-T2.genome',
 'Paenibacillus_sp._CF095_2690315662.fna',
 'Paenibacillus_sp._OK076_2690315677.fna',
 'Paenibacillus_sp._OK003_2687453683.fna',
 'Paenibacillus_sp._OV031_2616644976.fna',
 'Paenibacillus_sp._OK060_2684623002.fna',
 'FW126-L8.genome',
 'Cohnella_sp._OV330_2615840604.fna',
 'Cohnella_sp._OV312_2757320417.fna',
 'Paenibacillus_sp._CF384_2690315634.fna',
 'Paenibacillus_sp._BC26_2690315656.fna',
 'Paenibacillus_sp._OV219_2690315629.fna',
 'Paenibacillus_sp._BK736_2795386115.fna',
 'Paenibacillus_sp._OV191_2757320429.fna',
 'GCF_001422685.1.fna',
 'Paenibacillus_sp._BK033_2799112226.fna',
 'Paenibacillus_sp._BK720_2825305888.fna',
 'GCF_001423925.1.fna',
 'GCF_001423965.1.fna',
 'Fictibacillus_sp._BK138_2799112232.fna',
 'Bacillus_sp._OV194_2684622999.fna',
 '169963.11.RAST',
 '272626.9.RAST',
 '93062.19.RAST',
 'FW104-15G4D.genome',
 '586733.6.RAST',
 'Paenisporosarcina_sp._OV554_2738541299.fna',
 'Psychrobacillus_sp._OK032_2690315620.fna',
 'Psychrobacillus_sp._OK028_2687453675.fna',
 'Viridibacillus_sp._OK051_2716884256.fna',
 'GW247-5R2A.genome',
 'Lysinibacillus_sp._YR326_2615840593.fna',
 'Lysinibacillus_sp._BK089_2799112248.fna',
 'Bacillus_sp._OV322_2693429828.fna',
 'Bacillus_sp._OK838_2687453793.fna',
 'FW510-T9.genome',
 'EB106-08-03-XG77.genome',
 'Bacillus_sp._OV166_2716885053.fna',
 'EB106-08-02-XG196.genome',
 'Bacillus_sp._OK085_2738541295.fna',
 'Bacillus_sp._OK048_2687453680.fna',
 'Bacillus_sp._BK245_2799112205.fna',
 'Bacillus_sp._OV186_2738543017.fna',
 'genomeset_EB106-04-02-XG92.genome',
 'Bacillus_sp._OK077_2738543006.fna',
 'Bacillus_sp._OV752_2738541358.fna',
 'Bacillus_sp._OK061_2615840539.fna',
 'Bacillus_sp._YR331_2615840594.fna',
 'Bacillus_sp._OK634_2615840538.fna',
 'CPT56D-587-MTF.genome',
 'Bacillus_sp._BC15_2615840537.fna',
 'Bacillus_sp._YR288_2716884857.fna',
 'FW507-14D01.genome',
 'Bacillus_sp._BK006_2799112247.fna',
 'Bacillus_sp._YR335_2738543010.fna',
 'Bacillus_sp._BK100_2799112227.fna',
 '224308.43.RAST',
 '1178537.3.RAST',
 '1178544.5.RAST',
 '293387.10.RAST',
 'GCF_001426125.1.fna',
 '536229.4.RAST',
 'Bacillus_sp._BK450_2799112266.fna',
 '1178541.5.RAST',
 'GCF_001424455.1.fna',
 'GCF_001424485.1.fna',
 '38305.14.RAST',
 'GCF_001424365.1.fna',
 '262316.17.RAST',
 'Mycobacterium_sp._BK558_2799112228.fna',
 'GW460-12-10-14-LB6.genome',
 'Mycobacterium_sp._OK889_2738541264.fna',
 'Mycobacterium_sp._OK887_2738541356.fna',
 '1763.1022.RAST',
 'Mycobacterium_sp._YR708_2738541274.fna',
 'Mycobacterium_sp._YR782_2738543028.fna',
 'Mycobacterium_sp._BK086_2799112245.fna',
 'Mycolicibacterium_sp._BK634_2825252539.fna',
 'Mycolicibacterium_sp._BK607_2825215390.fna',
 'Mycolicibacterium_sp._BK598_2825202462.fna',
 'Mycolicibacterium_sp._BK557_2825179492.fna',
 'Mycolicibacterium_sp._BK556_2825172686.fna',
 '191292.16.RAST',
 '2508718.3.RAST',
 'Rhodococcus_sp._OK269_2738543034.fna',
 'GCF_001426085.1.fna',
 'GCF_001426165.1.fna',
 'GCF_001426145.1.fna',
 'GCF_001425985.1.fna',
 'GCF_001426185.1.fna',
 'Rhodococcus_sp._OK519_2738543005.fna',
 'Rhodococcus_sp._OK611_2738543011.fna',
 'Rhodococcus_sp._OK270_2737472030.fna',
 '37919.10.RAST',
 'Rhodococcus_sp._OK551_2738541308.fna',
 'Rhodococcus_sp._OK302_2713897328.fna',
 'FW305-104.genome',
 'FW305-130.genome',
 'MPR-R1B.genome',
 'MPR-R3B.genome',
 'MPR-R1A.genome',
 'GCF_916858655.1.fna',
 'GCF_001423365.1.fna',
 'GCF_001422865.1.fna',
 'GCF_001423335.1.fna',
 'GCF_001422765.1.fna',
 'GCF_942548115.1.fna',
 'GCF_001424755.1.fna',
 'GCF_916862475.1.fna',
 'GCF_001423135.1.fna',
 'GCF_001422955.1.fna',
 'Nocardioides_sp._CF479_2739367898.fna',
 'Nocardioides_sp._CF167_2738541305.fna',
 'Nocardioides_sp._CF204_2739367862.fna',
 'Nocardioides_sp._YR527_2684622998.fna',
 'Kitasatospora_sp._OK780_2718217689.fna',
 'Streptomyces_sp._BK215_2802428825.fna',
 'Actinobacteria_bacterium_OV450_2639763148.fna',
 'Streptomyces_sp._BK038_2795386112.fna',
 'Streptomyces_sp._BK438_2795386135.fna',
 'Streptomyces_atratus_OK807_2616644941.fna',
 'Streptomyces_atratus_OK008_2582581312.fna',
 'Streptomyces_sp._OK210_2615840540.fna',
 'Streptomyces_mirabilis_YR139_2582581314.fna',
 'Actinobacteria_bacterium_OK074_2639762959.fna',
 'Streptomyces_sp._OK885_2716884858.fna',
 'Streptomyces_mirabilis_OK461_2616644814.fna',
 'Streptomyces_sp._OV198_2718217699.fna',
 'Streptomyces_sp._OK228_2721755846.fna',
 'Actinobacteria_bacterium_OK006_2639763183.fna',
 '1883.1831.RAST',
 '1883.1832.RAST',
 '1883.1827.RAST',
 'Streptomyces_sp._BK022_2799112265.fna',
 'Streptomyces_sp._BK447_2795386113.fna',
 'Streptomyces_sp._CF124_2609459763.fna',
 'Streptomyces_sp._BK161_2795386114.fna',
 'Streptomyces_sp._BK561_2795386110.fna',
 'Streptomyces_sp._BK239_2799112261.fna',
 'Actinobacteria_bacterium_OV320_2634166429.fna',
 'Streptomyces_sp._YR375_2615840635.fna',
 '1883.1829.RAST',
 'Streptomyces_sp._BK308_2795386111.fna',
 'Streptomyces_sp._BK340_2795386105.fna',
 'Streptomyces_sp._BK387_2795386134.fna',
 'Streptomyces_sp._BK141_2795386108.fna',
 'Streptomyces_sp._CF386_2615840541.fna',
 'Streptomyces_sp._BK208_2795386122.fna',
 'Streptomyces_sp._BK335_2795386107.fna',
 'Streptomyces_sp._BK674_2795386116.fna',
 'Streptomyces_sp._BK329_2795386109.fna',
 'Streptomyces_sp._BK042_2795386124.fna',
 'Streptomyces_sp._BK205_2795386106.fna',
 '2306165.4.RAST',
 'Streptomyces_mirabilis_OV308_2582581313.fna',
 'MPR-E5.genome',
 'FW104-15G4B.genome',
 'GW247-C5.genome',
 'Promicromonospora_sp._YR516_2739367654.fna',
 'Promicromonospora_sp._CF082_2738543027.fna',
 'Promicromonospora_sp._AC04_2738541272.fna',
 'GCF_001425965.1.fna',
 '1707.13.RAST',
 'GCF_001424195.1.fna',
 'GCF_001424125.1.fna',
 'MPR-LB2.genome',
 'Kocuria_sp._OV113_2739367653.fna',
 'GCF_001422665.1.fna',
 'FW306-04-A.genome',
 '1663.242.RAST',
 'FW306-2-2C-B10A.genome',
 'FW306-2-2C-D06B.genome',
 'FW306-1B-F12A.genome',
 'FW306-1B-G06A.genome',
 '1663.245.RAST',
 '1663.236.RAST',
 '1663.241.RAST',
 '1663.234.RAST',
 '1663.228.RAST',
 'Arthrobacter_sp._YR096_2615840638.fna',
 'Arthrobacter_sp._CF158_2615840536.fna',
 'FW305-123.genome',
 '1663.235.RAST',
 '1663.218.RAST',
 '1663.201.RAST',
 '1663.205.RAST',
 '1663.248.RAST',
 '1663.230.RAST',
 '1663.237.RAST',
 '1663.238.RAST',
 '1663.250.RAST',
 'GCF_001424565.1.fna',
 'Arthrobacter_sp._OV608_2687453691.fna',
 '2590785.4.RAST',
 'FW306-05-C.genome',
 '2590785.5.RAST',
 '1663.229.RAST',
 'GCF_001422645.1.fna',
 'Arthrobacter_sp._OK362_2609459768.fna',
 'Arthrobacter_sp._OV407_2609459738.fna',
 'Arthrobacter_sp._OK909_2609459742.fna',
 'Arthrobacter_sp._OV118_2609459726.fna',
 '1663.233.RAST',
 '33882.147.RAST',
 'GCF_001423745.1.fna',
 'GW460-12-1-14-TSB2.genome',
 'FW305-BF8.genome',
 '1357915.4.RAST',
 '1663.203.RAST',
 '1663.246.RAST',
 '1663.224.RAST',
 '1663.231.RAST',
 '1663.219.RAST',
 '1663.226.RAST',
 '1663.247.RAST',
 '1663.222.RAST',
 '1663.232.RAST',
 '1663.207.RAST',
 '1663.209.RAST',
 '1663.239.RAST',
 '1663.225.RAST',
 '1663.251.RAST',
 'Microbacterium_sp._BK664_2799112235.fna',
 '104336.22.RAST',
 '104336.19.RAST',
 '33882.143.RAST',
 '33882.145.RAST',
 '33882.144.RAST',
 'GCF_001423485.1.fna',
 'GCF_001423615.1.fna',
 'GCF_001423645.1.fna',
 '104336.18.RAST',
 '104336.20.RAST',
 '104336.16.RAST',
 '104336.17.RAST',
 '104336.21.RAST',
 'Microbacterium_sp._CF332_2609459766.fna',
 'MPR-TSA4.genome',
 'MPR-R2A2.genome',
 'Microbacterium_sp._CF335_2585428157.fna',
 'GCF_001423825.1.fna',
 'GCF_001423805.1.fna',
 'Microbacterium_sp._CF046_2609459760.fna',
 'GCF_001422925.1.fna',
 'Microbacterium_sp._BK668_2799112233.fna',
 'FW305-3-2-15-F-LB2.genome',
 'GCF_001421275.1.fna',
 'GCF_001424225.1.fna',
 'GCF_001423785.1.fna',
 'GCF_001424715.1.fna',
 'Leifsonia_sp._BK543_2799113267.fna',
 'GCF_001422205.1.fna',
 'GCF_001424385.1.fna',
 'Curtobacterium_sp._YR515_2616644843.fna',
 'GCF_001424595.1.fna',
 'GCF_001423105.1.fna',
 'GCF_001423665.1.fna',
 'GCF_001424285.1.fna',
 'GCF_001422285.1.fna',
 'GCF_001423905.1.fna',
 'GCF_001421165.1.fna',
 'GCF_001421865.1.fna',
 'GCF_001424645.1.fna',
 'GCF_001422145.1.fna',
 '110932.16.RAST',
 '110932.17.RAST',
 '110932.15.RAST',
 'GCF_001423695.1.fna',
 'GCF_001423005.1.fna',
 'GCF_001423885.1.fna',
 'GCF_001423045.1.fna',
 'GCF_001423055.1.fna',
 'GCF_920939495.1.fna',
 'FW305-C-112.genome',
 'GCF_001421485.1.fna',
 'GCF_001422695.1.fna',
 'GCF_001422485.1.fna',
 'Plantibacter_sp._YR521_2758568592.fna',
 'GCF_001423185.1.fna',
 'GCF_001423725.1.fna',
 'Agromyces_sp._OV415_2757320520.fna',
 'Agromyces_sp._OV568_2757320573.fna',
 'Agromyces_sp._CF514_2690315658.fna',
 'Agromyces_sp._OV429_2757320537.fna',
 'GCF_001421565.1.fna',
 'Microterricola_sp._OV434_2758568040.fna',
 'Herbiconiux_sp._YR403_2585428094.fna',
 'GCF_001423545.1.fna',
 'GCF_001422325.1.fna',
 'Leifsonia_sp._OV430_2758568661.fna',
 '85963.7.RAST',
 '85963.30.RAST',
 '1321939.6.RAST',
 '210.1972.RAST',
 '210.1978.RAST',
 '1311573.5.RAST',
 '1321940.7.RAST',
 '1321940.5.RAST',
 '1412896.3.RAST',
 '1412897.3.RAST',
 '192222.6.RAST',
 '1365659.3.RAST',
 '1365657.3.RAST',
 '1367443.3.RAST',
 '1365661.3.RAST',
 '407148.6.RAST',
 'Asticcacaulis_sp._CF398_2739367756.fna',
 'GCF_001424025.1.fna',
 'GW456-12-10-14-LB3.genome',
 'GW460-12-10-14-LB2.genome',
 'GCF_001423685.1.fna',
 'GCF_001422455.1.fna',
 'GW456-12-1-14-TSB4.genome',
 '565050.3.RAST',
 'Caulobacter_sp._OV484_2585428106.fna',
 'Caulobacter_henricii_OK261_2582581279.fna',
 'Caulobacter_sp._AP07_2510917020.fna',
 'Caulobacter_sp._BK020_2795386129.fna',
 'Caulobacter_henricii_CF287_2582581280.fna',
 'Caulobacter_henricii_YR570_2582581293.fna',
 '192.7.RAST',
 'FW306-1B-F04DB.genome',
 'Sphingomonas_wittichii_YR128_2582581305.fna',
 'Sphingomonas_sp._YR710_2687453684.fna',
 '1219046.3.RAST',
 'FW306-1B-B10E.genome',
 'Sphingomonas_sp._CF311_2758568039.fna',
 'GCF_001421635.1.fna',
 'GCF_920939515.1.fna',
 'GCF_001421845.1.fna',
 'GCF_001425385.1.fna',
 'GCF_001421245.1.fna',
 'GCF_001421965.1.fna',
 'GCF_001421715.1.fna',
 'GCF_001421605.1.fna',
 'GCF_001421155.1.fna',
 'GCF_001421765.1.fna',
 'GCF_001421405.1.fna',
 'GCF_001421585.1.fna',
 'GCF_001421285.1.fna',
 'GCF_001421355.1.fna',
 'GCF_001423845.1.fna',
 'Sphingomonas_sp._OV641_2684623004.fna',
 'GCF_001425405.1.fna',
 'Sphingomonas_sp._BK580_2825186326.fna',
 'Sphingomonas_sp._BK235_2795386133.fna',
 'Sphingomonas_sp._BK069_2824931730.fna',
 'Sphingomonas_sp._BK345_2825022033.fna',
 'GCF_001422185.1.fna',
 'GCF_916858675.1.fna',
 'GCF_001426195.1.fna',
 'GCF_920939475.1.fna',
 'GCF_001421505.1.fna',
 'GCF_001421535.1.fna',
 'Sphingomonas_sp._BK481_2825131734.fna',
 'GCF_001421625.1.fna',
 'GCF_001422525.1.fna',
 'Sphingomonas_sp._BK036_2799112244.fna',
 'GCF_001421825.1.fna',
 'GCF_001421805.1.fna',
 'GCF_001422045.1.fna',
 'GCF_001421745.1.fna',
 'GCF_001421415.1.fna',
 'Sphingomonas_sp._OK281_2690315632.fna',
 'GCF_920984725.1.fna',
 'GCF_001424005.1.fna',
 '13689.6.RAST',
 'Sphingobium_sp._YR657_2687453679.fna',
 'Sphingobium_sp._AP49_2512564014.fna',
 'GW456-12-10-14-TSB1.genome',
 'GW460-11-11-14-TSB6.genome',
 'GCF_001421665.1.fna',
 'Sphingobium_sp._AP50_2687453790.fna',
 'Sphingobium_sp._YR768_2687453792.fna',
 'Sphingopyxis_sp._YR583_2687453811.fna',
 'GW247-27LB.genome',
 'GW247-3R2A.genome',
 'Novosphingobium_sp._GV010_2757320443.fna',
 'Novosphingobium_sp._CF614_2687453689.fna',
 '158500.12.RAST',
 'Novosphingobium_sp._AP12_2510917021.fna',
 'GCF_001421325.1.fna',
 'genomeset_FW305-C-30-35.genome',
 'FW305-C-111.genome',
 'Novosphingobium_sp._GV013_2739367865.fna',
 'Novosphingobium_sp._GV002_2739367664.fna',
 'Novosphingobium_sp._GV055_2738543022.fna',
 'Novosphingobium_sp._GV079_2738541301.fna',
 'Novosphingobium_sp._GV070_2757320420.fna',
 'Novosphingobium_sp._GV064_2738543033.fna',
 'Novosphingobium_sp._GV078_2757320426.fna',
 'Novosphingobium_sp._GV011_2757320424.fna',
 'Novosphingobium_sp._GV076_2757320421.fna',
 'Novosphingobium_sp._GV026_2757320425.fna',
 'Novosphingobium_sp._GV061_2738541304.fna',
 'Novosphingobium_sp._GV057_2757320435.fna',
 'Novosphingobium_sp._GV022_2757320419.fna',
 'Novosphingobium_sp._GV027_2738541275.fna',
 'Novosphingobium_sp._BK256_2824936341.fna',
 'Novosphingobium_sp._BK349_2825032682.fna',
 'Novosphingobium_sp._BK431_2825105165.fna',
 'Novosphingobium_sp._BK455_2825114065.fna',
 'Novosphingobium_sp._BK592_2825198029.fna',
 'Novosphingobium_sp._BK280_2824955886.fna',
 'Novosphingobium_sp._BK258_2824940795.fna',
 'Novosphingobium_sp._BK486_2825136299.fna',
 'Novosphingobium_sp._BK540_2825168233.fna',
 'Novosphingobium_sp._BK448_2825109614.fna',
 'Novosphingobium_sp._BK409_2825096259.fna',
 'Novosphingobium_sp._BK361_2825041588.fna',
 'Novosphingobium_sp._BK727_2825301438.fna',
 'Novosphingobium_sp._BK679_2825276256.fna',
 'Novosphingobium_sp._BK430_2825100708.fna',
 'Novosphingobium_sp._BK626_2825248085.fna',
 'Novosphingobium_sp._BK352_2825037131.fna',
 'Novosphingobium_sp._BK267_2824945254.fna',
 'Novosphingobium_sp._BK657_2825265993.fna',
 'Novosphingobium_sp._BK369_2825006728.fna',
 'Novosphingobium_sp._BK401_2825091808.fna',
 'Novosphingobium_sp._BK336_2825011164.fna',
 '398580.10.RAST',
 '391619.3.RAST',
 'Devosia_sp._YR412_2690315612.fna',
 'GCF_001421945.1.fna',
 'GCF_001425445.1.fna',
 'FW305-C-134A.genome',
 'Tardiphaga_sp._CF115_2758568495.fna',
 'Tardiphaga_sp._OV697_2757320514.fna',
 'Tardiphaga_sp._YR296_2758568519.fna',
 'Tardiphaga_sp._OK245_2609459751.fna',
 'Tardiphaga_sp._OK246_2609459765.fna',
 'Bradyrhizobium_sp._YR681_2511231028.fna',
 'Bradyrhizobium_sp._OK095_2687453685.fna',
 'Bradyrhizobium_sp._CF659_2609459633.fna',
 'Bradyrhizobium_sp._BK707_2799112246.fna',
 'GCF_001424605.1.fna',
 'GCF_920939485.1.fna',
 'FW305-C-101.genome',
 'Bosea_sp._BK498_2799112242.fna',
 '85413.36.RAST',
 'Bosea_sp._OK403_2609459641.fna',
 'GCF_001426225.1.fna',
 'Bosea_sp._CF476_2757320442.fna',
 'Bosea_sp._BK604_2795386121.fna',
 'Methylobacterium_sp._YR596_2615840644.fna',
 'Methylobacterium_sp._AP11_2609459615.fna',
 'GCF_920984675.1.fna',
 'GCF_001424445.1.fna',
 'Methylobacterium_sp._YR668_2609459632.fna',
 'Methylobacterium_sp._BK227_2795386104.fna',
 'GCF_001425565.1.fna',
 'GCF_001424525.1.fna',
 'GCF_001423265.1.fna',
 'GCF_001422815.1.fna',
 'GCF_001422165.1.fna',
 'GCF_001422345.1.fna',
 'GCF_001422895.1.fna',
 'GCF_001422125.1.fna',
 'GCF_001422375.1.fna',
 'GCF_001423295.1.fna',
 'GCF_001422775.1.fna',
 'GCF_001422425.1.fna',
 'GCF_001422845.1.fna',
 'GCF_001424745.1.fna',
 'GCF_001422985.1.fna',
 'GCF_001422885.1.fna',
 'FW306-05-D.genome',
 'Methylobacterium_sp._GV104_2738543032.fna',
 'Methylobacterium_sp._GV094_2738541281.fna',
 'GCF_001426045.1.fna',
 'GCF_001423285.1.fna',
 'GCF_001422795.1.fna',
 'GCF_001424705.1.fna',
 'GCF_001422215.1.fna',
 'Pleomorphomonas_sp._CF100_2738543031.fna',
 'GCF_001425575.1.fna',
 'GCF_001423245.1.fna',
 'GCF_001424685.1.fna',
 'GCF_001425485.1.fna',
 'GCF_001425525.1.fna',
 'Phyllobacterium_sp._YR620_2690315616.fna',
 '28100.10.RAST',
 'Phyllobacterium_sp._OV277_2687453676.fna',
 'Phyllobacterium_sp._YR531_2511231027.fna',
 'Mesorhizobium_sp._YR577_2687453760.fna',
 'Aminobacter_sp._AP02_2738543024.fna',
 'Mesorhizobium_sp._AP09_2758568520.fna',
 '381.96.RAST',
 '266834.11.RAST',
 'Ensifer_sp._AP48_2757320415.fna',
 'Ensifer_sp._YR511_2615840643.fna',
 'Ensifer_sp._OV372_2609459711.fna',
 'GCF_001424045.1.fna',
 'GCF_001424325.1.fna',
 'GCF_001425345.1.fna',
 'GCF_001424085.1.fna',
 'GCF_001425605.1.fna',
 'Rhizobium_sp._CF097_2582581866.fna',
 'Rhizobium_sp._OK665_2582581283.fna',
 'Rhizobium_sp._YR295_2582581306.fna',
 'Rhizobium_sp._CF258_2582581865.fna',
 'Rhizobium_sp._PDO1-076_2510461069.fna',
 'Rhizobium_sp._PDC82_2690315628.fna',
 'GCF_001422245.1.fna',
 'GCF_001423445.1.fna',
 'Rhizobium_sp._CF080_2562617114.fna',
 'GCF_001423425.1.fna',
 'GCF_001423215.1.fna',
 'Rhizobium_sp._BK376_2795386123.fna',
 '379.412.RAST',
 'Rhizobium_sp._BK333_2799112289.fna',
 'Rhizobium_sp._BK313_2824979408.fna',
 'Rhizobium_sp._BK602_2825209331.fna',
 'Agrobacterium_rhizogenes_OK036_2582581316.fna',
 'Agrobacterium_rhizogenes_YR147_2582581315.fna',
 'Rhizobium_lusitanum_YR374_2585427527.fna',
 'Rhizobium_sp._OK494_2582581308.fna',
 'Rhizobium_tropici_YR635_2585427530.fna',
 'Agrobacterium_rhizogenes_OV677_2585427608.fna',
 'Rhizobium_sp._AP16_2510917022.fna',
 'Agrobacterium_rhizogenes_YR530_2585427531.fna',
 'Rhizobium_sp._YR060_2582581307.fna',
 'Agrobacterium_rhizogenes_CF262_2585428125.fna',
 'Agrobacterium_rhizogenes_CF263_2585427609.fna',
 'Rhizobium_sp._BK386_2825065874.fna',

In [50]:
def prune_tree(tree, dataset_to_keep, common_index):
    if dataset_to_keep == "at_leaf":
        for leaf in tree:
            if leaf.name.startswith("GCF"):
                leaf.name = leaf.name.rstrip(".fna")
            else:
                leaf.delete()
    elif dataset_to_keep == "literature":
        for leaf in tree:
            if leaf.name.endswith("RAST"):
                leaf.name = leaf.name.rstrip(".RAST")
            else:
                leaf.delete()
    else:
        raise ValueError("dataset_to_keep must be either 'at_leaf' or 'literature'")
    # Are all the leaves in our tree present in common_index?
    is_subset = set([leaf.name for leaf in tree]) <= set(common_index)
    if not is_subset:
        # remove leaves that are not in the common_index
        tree_leaves_not_in_index = set([leaf.name for leaf in tree]) - set(common_index)
        for leaf in tree_leaves_not_in_index:
            tree.search_nodes(name=leaf)[0].delete()

In [51]:
prune_tree(tree, "at_leaf", common_index)

In [52]:
# new number of leaves in tree
len(tree)

175

In [53]:
final_common_index = set([leaf.name for leaf in tree])

### Random split

In [54]:
random_splitter = RandomSplitter(test_set_ratio=0.2)
samples = list(final_common_index)
test_samples_rs = random_splitter.split(samples)
train_samples_rs = list(set(samples) - set(test_samples_rs))

In [55]:
X_train_rs = X.loc[train_samples_rs]
X_test_rs = X.loc[test_samples_rs]
y_train_rs = y.loc[train_samples_rs]
y_test_rs = y.loc[test_samples_rs]
print(X_train_rs.shape, X_test_rs.shape, y_train_rs.shape, y_test_rs.shape)

(140, 1000) (35, 1000) (140,) (35,)

### Out-of-clade split

In [56]:
ooc_splitter = LargeTreeTraverseOOCSplitter(
    tree,
    test_set_range=(0.2, 0.3),
    single_clades=None,
    n_max_clade=2,
    prefer_small_clade=False,
    growth_data=None,
    min_zeros=0,
    min_ones=0,
    time_out_iter=None,
)
samples = list(final_common_index)
test_samples_ooc = ooc_splitter.split(samples)
train_samples_ooc = list(set(samples) - set(test_samples_ooc))

In [57]:
X_train_ooc = X.loc[train_samples_ooc]
X_test_ooc = X.loc[test_samples_ooc]
y_train_ooc = y.loc[train_samples_ooc]
y_test_ooc = y.loc[test_samples_ooc]
print(X_train_ooc.shape, X_test_ooc.shape, y_train_ooc.shape, y_test_ooc.shape)

(134, 1000) (41, 1000) (134,) (41,)

## Is the OOC split choosing different samples each time?

In [58]:
import random
from functools import reduce

def get_clades(single_clades, test_set_range, samples):
    while True:
        clades = random.sample(single_clades, 2)
        test_samples = reduce(np.union1d, clades)
        if (len(test_samples) / len(samples)) < test_set_range[0] or (
            len(test_samples) / len(samples)
        ) > test_set_range[1]:
            continue
        else:
            break
    return test_samples

In [59]:
test_set_range = (0.2, 0.3)
single_clades = ooc_splitter.compute_single_clades(tree, samples)

print(f"Number of single clades = {len(single_clades)}")

clades_1 = get_clades(single_clades, test_set_range, samples)
clades_2 = get_clades(single_clades, test_set_range, samples)
common_elements = set(clades_1) & set(clades_2)
perc_common = len(common_elements) / min(len(clades_1), len(clades_2)) * 100
print(f"Percentage of common elements = {perc_common}")

Number of single clades = 168
Percentage of common elements = 94.44444444444444

Yes, sometimes it does.

## Machine learning performance

In [60]:
from catboost import CatBoostClassifier
def make_classifier(random_state: int, categorical_feature_names: list[str] | None):
    """
    Creates a classifier.

    Parameters
    ---------
    random_state : int
        Random state.
    categorical_feature_names : list[str] | None
        List of categorical feature names.

    Returns
    ------
    Classifier object.
    """
    clf = CatBoostClassifier(
        # iterations=1000,
        # depth=8,
        # learning_rate=0.03,
        # l2_leaf_reg=3,
        # bootstrap_type="Bayesian",
        # bagging_temperature=1,
        random_state=random_state,
        objective="Logloss",
        cat_features=categorical_feature_names,
        verbose=False,
        allow_writing_files=False,
        thread_count=1,
    )
    return clf

In [61]:
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    f1_score,
    matthews_corrcoef,
    precision_score,
    recall_score,
)
def get_scores(
    y_true: pd.Series, y_pred: pd.Series, index_name: str
) -> pd.DataFrame:
    """
    Calculates the scores for the given true and predicted labels.

    Parameters
    ---------
    y_true : pd.DataFrame
        True labels.
    y_pred : pd.DataFrame
        Predicted labels.

    Returns
    ------
    pd.DataFrame
        Scores.
    """
    scores = {
        "accuracy": accuracy_score(y_true, y_pred),
        "balanced_accuracy": balanced_accuracy_score(y_true, y_pred),
        "f1": f1_score(y_true, y_pred),
        "precision": precision_score(y_true, y_pred),
        "recall": recall_score(y_true, y_pred),
        "matthews_corrcoef": matthews_corrcoef(y_true, y_pred),
    }
    return pd.DataFrame(scores, index=[index_name])

In [62]:
categorical_feature_names = list(X.columns)
clf_rs = make_classifier(42, categorical_feature_names)
clf_ooc = make_classifier(42, categorical_feature_names)

### Random split performance

In [63]:
clf_rs.fit(X_train_rs, y_train_rs)
y_predict_rs = clf_rs.predict(X_test_rs)

In [64]:
scores_rs = get_scores(y_test_rs, y_predict_rs, "random split")
scores_rs

,accuracy,balanced_accuracy,f1,precision,recall,matthews_corrcoef
random split,0.885714,0.889803,0.882353,0.833333,0.9375,0.777053

random split	0.888889	0.896104	0.904762	0.95	0.863636	0.777212

### OOC split performance

In [65]:
clf_ooc.fit(X_train_ooc, y_train_ooc)
y_predict_ooc = clf_ooc.predict(X_test_ooc)

In [66]:
scores_ooc = get_scores(y_test_ooc, y_predict_ooc, "ooc split")
scores_ooc

,accuracy,balanced_accuracy,f1,precision,recall,matthews_corrcoef
ooc split,0.829268,0.651042,0.461538,0.75,0.333333,0.421398

ooc split	0.761905	0.814815	0.75	0.6	1.0	0.614636

## Features

In [67]:
# Get the top 10 most important features
clf_rs.get_feature_importance(prettified=True)[:10]

  Feature Id  Importances
0     K01271     5.008399
1     K00459     2.425798
2     K01969     1.879603
3     K22210     1.870121
4   K03453.1     1.710666
5  952_631.1     1.610139
6     K05989     1.373288
7     K01692     1.294914
8     K09764     1.244509
9     K01637     1.243259

In [68]:
clf_ooc.get_feature_importance(prettified=True)[:10]

  Feature Id  Importances
0   K01637.1     3.299178
1     K00854     3.010258
2     K01637     2.907888
3     K07481     2.416218
4   K21686.1     2.109997
5   K09764.1     1.863118
6     K09764     1.831932
7   K03453.1     1.320571
8     K19221     1.102433
9     K00459     1.039242